version: "3.8"

services:
  react-app:
    build: .
    container_name: portfolio_app
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`sofiane-kherarfa.azim404.com`) || Host(`azim404.com`) || Host(`www.azim404.com`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true
